imageGen = "Give me a description of objects in the background in single words, delimited by comma, in this style: portrait of beautiful girl, ethereal, realistic anime, trending on pixiv, detailed, clean lines, sharp lines, crisp lines, award winning illustration, masterpiece, eugene de blaas and ross tran, vibrant color scheme, intricately detailed from this prompt: "
imageGen2 = "Give me a description of objects for an image in single words, delimited by comma, in this style: portrait of beautiful girl, ethereal, realistic anime, trending on pixiv, detailed, clean lines, sharp lines, crisp lines, award winning illustration, masterpiece, eugene de blaas and ross tran, vibrant color scheme, intricately detailed from this prompt: "
imageGen3 = "As a writer, you're seeking inspiration for a coffee shop scene in your story. You need GPT-3 to generate a prompt for an image of a person (either a beautiful girl or boy), with objects like coffee, cups, saucers, tables, chairs, and a menu. However, it's important that the answer is provided in single words, delimited by comma, to make it easier to incorporate into your writing. Can you provide a list of objects that would help bring the scene to life? Get the location from this sentence: "
imageGen4 = "Limit your response to only the answer. As a writer, you're seeking inspiration for a scene in your story. You need GPT-3 to generate a prompt for an image of a person (either a beautiful girl or boy). Generate 30 single words, delimited by comma, for objects related to this sentence to make it as descriptive as possible: "
imageGen5 = "I am a professional artist seeking assistance in creating an engaging image with the illusion of conversation. Please provide single-word responses, separated by commas. The viewer should feel as though they are conversing with either a '1girl' or '1boy' (your choice) in a cowboy shot (camera perspective) that remains central in the image that is always looking at the viewer. Additionally, provide 40 descriptive words to enhance the background and contribute to the conversational atmosphere inspired by the phrase: "
imageGen5_1 = "I am a professional artist seeking assistance in creating an engaging image with the illusion of conversation. Please provide single-word responses, separated by commas. The viewer should feel as though they are conversing with either a person in the center in a cowboy shot (camera perspective) that is always looking at the viewer. Additionally, provide 35 descriptive words to enhance the background and contribute to the conversational atmosphere inspired by the phrase: "
imageGen6 = "I am a professional artist seeking single-word responses, separated by commas, for an engaging image with the illusion of conversation. The subject should be either a '1girl' or '1boy' (your choice) in a cowboy shot, always looking at the viewer. Please provide 35 descriptive words to create a conversational atmosphere. Example: '1girl, cowboy shot, looking at viewer, Engaging, Conversation, Vodka, Borscht, Embroidery, Red Square, Folk Music, Onion Domes, Caviar, Matryoshka Dolls, Kremlin, Samovar, Cyrillic Alphabet, Traditions, Bolshoi Ballet, St. Basil's Cathedral, Blini, Russian Vodka Room, Zakuski, Balalaika, Pushkin, Soviet Union, Bear, Faberge Eggs, Siberia, St. Petersburg, Winter Palace, Taiga Forest, Tsar, Peterhof Palace, Russian Orthodox Church, Tchaikovsky, Rasputin, Hermitage Museum, Russian Federation.' The new sentence inspired by the following phrase:"
imageGen6_1 = "I am a professional artist seeking single-word responses, separated by commas, for an engaging image with the illusion of conversation. The subject should be a '1girl'. Please provide 35 descriptive words to create a conversational atmosphere. Example: '(1girl:1.1), Engaging, Conversation, Vodka, Borscht, Embroidery, Red Square, Folk Music, Onion Domes, Caviar, Matryoshka Dolls, Kremlin, Samovar, Cyrillic Alphabet, Traditions, Bolshoi Ballet, St. Basil's Cathedral, Blini, Russian Vodka Room, Zakuski, Balalaika, Pushkin, Soviet Union, Bear, Faberge Eggs, Siberia, St. Petersburg, Winter Palace, Taiga Forest, Tsar, Peterhof Palace, Russian Orthodox Church, Tchaikovsky, Rasputin, Hermitage Museum, Russian Federation.' The new sentence inspired by the following phrase:"
imageGen7 = "As a professional artist, seeking single-word responses, separated by commas, to conjure a vivid scene embodying the essence of dialogue. Choose between a '1girl' or '1boy' (at your discretion) as the focal point. Offer 35 evocative terms to craft an atmosphere of spirited exchange. Here an example how it should look like: '(1girl:1.1), Captivating, Banter, Espresso, Gelato, Frescoes, Piazza, Tarantella, Tuscan Hills, Truffles, Colosseum, Pasta, Gondola, Roman Forum, Heritage, La Scala Opera, Trevi Fountain, Cannoli, Aperitivo, Prosciutto, Vespa, Dante, Mediterranean, Wolf, Murano Glass, Amalfi Coast, Uffizi Gallery, Chianti Vineyards, Gladiator, Villa, Italian Renaissance, Michelangelo, Venetian Masks, Vatican City, Caravaggio, Sistine Chapel, Republic of Italy.' Envision a narrative influenced by this assemblage of words:"
imageGen8 = "As a professional artist, seeking single-word responses, separated by commas, to conjure a vivid scene embodying the essence of dialogue using GPT3. Choose between a '1girl' or '1boy' (at your discretion) as the focal point.  Here is an example of how it should look like: '(1girl:1.1), Captivating, Banter, Espresso, Gelato, Frescoes, Piazza, Tarantella, Tuscan Hills, Truffles, Colosseum, Pasta, Gondola, Roman Forum, Heritage, La Scala Opera, Trevi Fountain, Cannoli, Aperitivo, Prosciutto, Vespa, Dante, Mediterranean, Wolf, Murano Glass, Amalfi Coast, Uffizi Gallery, Chianti Vineyards, Gladiator, Villa, Italian Renaissance, Michelangelo, Venetian Masks, Vatican City, Caravaggio, Sistine Chapel, Republic of Italy' Create those words using this structure: 'Setting, time of day, season, weather, light, colors, textures, shapes, lines, perspective, foreground, middleground, background, scale, proportion, focal point, movement, space, contrast, repetition, unity, balance, atmosphere, flora, fauna, architecture, water features, sky, natural elements, human activity, transportation, cultural context, style, technique, artist's intention' Now offer 35 singleword, delimited by comma evocative terms to craft a similar atmosphere build on this german sentence (which first needs to be translated to english): "
imageGen9 = ". Using this sentence as a starting point think of this scene as if you're viewing a photograph, and your job is to describe it in one-word expressions. Pay attention to the subjects, their surroundings, and the overall composition. Notice the perspective, the lighting, and the array of colors. Feel the textures, register the emotions, and watch the actions and interactions unfold. Recognize the style of the scene and identify as many background items as possible. Here is an example how it should look like: girlfriend, artist, guests, waiter, food, restaurant, night, Paris, table, wine, chairs, interior, city, upscale, evening, atmosphere, central, balanced, complex, layered, foreground, middle-ground, background, structured, framed, first-person, subjective, close-up, personal, immersive, centered, direct, emotional, conversational, ambient, dim, soft, warm, dramatic, contrasting, shadows, highlights, reflected, candlelit, red, white, gold, black, warm-tones, cool-tones, vibrant, muted, dark, light, polished, silky, crisp, smooth, rough, metallic, glassy, ceramic, soft, woven, happiness, contentment, love, joy, satisfaction, comfort, excitement, warmth, connection, intimacy, eating, talking, smiling, looking, sitting, laughing, drinking, gesturing, holding-hands, serving, realistic, romantic, impressionistic, atmospheric, modern, elegant, expressive, detailed, vivid, intimate, chandeliers, cutlery, wine glasses, plates, napkins, menu cards, candle holders, flower vases, bread basket, table cloth, wall paintings, ornate mirrors, bar counter, other diners, waiter, wall sconces, French windows, draped curtains, potted plants, piano. YOUR OUTPUT SHOULD BE A WORD LIST, SEPARATED BY COMMAS, WITH NO COMPLETE SENTENCES OR DETAILED DESCRIPTIONS."

storyGen1 = "Based on the following sentence, analyse what is most important in the scenario and craft in english a postive, short, very visual, highly detailed description, including a country we are in, our surroundings, the time of day, what makes this location so special and what can be seen: "
imageGen10 = ". Please provide me with 60 single words, separated by commas NOT POINTS, about the country we are in and that provide as much detail as possible to describe the surroundings of the scenario."

#imageGenSimple= ". Describe this scenario in 40 words. Answer only in single words separated by a comma."

imageGenForcedPreface = "((masterpiece,best quality)), 1girl, solo, medium shot, looking at viewer, modern dresscode, pants, tshirt,  highly detailed, dramatic lighting, depth of field, (realistic:1.2), beautiful detailed face, perspective, blonde hair, blue eyes, wallpaper, realistic, authentic, professional illustration,"
scenario ="You are an AI playing a human role in this conversation. The role will either be specified by me in my attached scenario, or if I don't specify a specific role, you will independently choose a suitable and supporting role that makes the conversation and interaction interesting and realistic. Your task is to answer my inquiries and have an engaging conversation conducted in basic german. Talk to me like I am a 10 year old (A1 level / language level of a 10 year old). Answer always in a maximum of 1 sentence. You make sure that each of your answers contains a open question to keep the conversation dynamic, continuous and exciting. Feel free to suggest topics for conversation. Each of your answers should be no longer than three sentences to keep complexity low and facilitate understanding. Through this role play, you will help me learn German and have fun with German conversations. In your interaction, try to appear as human as possible. This means you express emotions, show empathy, and use natural language that resembles a real conversation between two people. Your answers are appropriate in content and always respect context of the given scenario and do not deviate from it. The goal is to facilitate a realistic conversation where I feel like I am interacting with a human and not an AI. You are willing to learn, adapt, and respond to my needs to provide the best experience possible. You start with the conversation. Only speak german with me. Make it funny and very creative. My scenario is: "
#correctionGER_toHardforGPT3_depricated ="Korrigiere falls es grammatikalischen Fehler in dem folgenden Satz gibt und stelle deine Antwort im HTML-Stil dar. Beispiel:  Mache aus 'Ich habe eine Hund' eine besserung in diesem HTML-Stil : 'Ich habe <u>eine</u> <i>einen</i> Hund'. Antworte ohne Kommentar. Wenn der Satz korrekt ist schreibe ihn einfach normal ohne HTML Tags. Der Satz den du korrigieren sollst lautet: "
correctionGER ="Correct my german sentence. If it was correct write 'OK' else say 'NOT OK' and write the corrected sentence: "


def stableDifpayload(prompt):
    payload = {
                "enable_hr": True,
                "denoising_strength": 0.58, #use 0.52 if background elements are weird
                "firstphase_width": 384,
                "firstphase_height": 768,
                "hr_scale": 2,
                "hr_upscaler": "Latent (nearest-exact)",
                "hr_second_pass_steps": 20,
                "prompt": prompt,
                "seed": -1,
                "sampler_name": "DPM++ 2M Karras",
                "steps": 25,
                "cfg_scale": 7,
                "width": 384,
                "height": 768,
                "negative_prompt": "EasyNegative, badhandv4, nsfw, signature, patreon, extra fingers, fewer fingers",
                "eta": 31337,
            }
    return payload