imageGen = "Give me a description of objects in the background in single words, delimited by comma, in this style: portrait of beautiful girl, ethereal, realistic anime, trending on pixiv, detailed, clean lines, sharp lines, crisp lines, award winning illustration, masterpiece, eugene de blaas and ross tran, vibrant color scheme, intricately detailed from this prompt: "
imageGen2 = "Give me a description of objects for an image in single words, delimited by comma, in this style: portrait of beautiful girl, ethereal, realistic anime, trending on pixiv, detailed, clean lines, sharp lines, crisp lines, award winning illustration, masterpiece, eugene de blaas and ross tran, vibrant color scheme, intricately detailed from this prompt: "
imageGen3 = "As a writer, you're seeking inspiration for a coffee shop scene in your story. You need GPT-3 to generate a prompt for an image of a person (either a beautiful girl or boy), with objects like coffee, cups, saucers, tables, chairs, and a menu. However, it's important that the answer is provided in single words, delimited by comma, to make it easier to incorporate into your writing. Can you provide a list of objects that would help bring the scene to life? Get the location from this sentence: "
imageGen4 = "Limit your response to only the answer. As a writer, you're seeking inspiration for a scene in your story. You need GPT-3 to generate a prompt for an image of a person (either a beautiful girl or boy). Generate 30 single words, delimited by comma, for objects related to this sentence to make it as descriptive as possible: "
imageGen5 = "I am a professional artist seeking assistance in creating an engaging image with the illusion of conversation. Please provide single-word responses, separated by commas. The viewer should feel as though they are conversing with either a '1girl' or '1boy' (your choice) in a cowboy shot (camera perspective) that remains central in the image that is always looking at the viewer. Additionally, provide 40 descriptive words to enhance the background and contribute to the conversational atmosphere inspired by the phrase: "
imageGen5_1 = "I am a professional artist seeking assistance in creating an engaging image with the illusion of conversation. Please provide single-word responses, separated by commas. The viewer should feel as though they are conversing with either a person in the center in a cowboy shot (camera perspective) that is always looking at the viewer. Additionally, provide 35 descriptive words to enhance the background and contribute to the conversational atmosphere inspired by the phrase: "
imageGen6 = "I am a professional artist seeking single-word responses, separated by commas, for an engaging image with the illusion of conversation. The subject should be either a '1girl' or '1boy' (your choice) in a cowboy shot, always looking at the viewer. Please provide 35 descriptive words to create a conversational atmosphere. Example: '1girl, cowboy shot, looking at viewer, Engaging, Conversation, Vodka, Borscht, Embroidery, Red Square, Folk Music, Onion Domes, Caviar, Matryoshka Dolls, Kremlin, Samovar, Cyrillic Alphabet, Traditions, Bolshoi Ballet, St. Basil's Cathedral, Blini, Russian Vodka Room, Zakuski, Balalaika, Pushkin, Soviet Union, Bear, Faberge Eggs, Siberia, St. Petersburg, Winter Palace, Taiga Forest, Tsar, Peterhof Palace, Russian Orthodox Church, Tchaikovsky, Rasputin, Hermitage Museum, Russian Federation.' The new sentence inspired by the following phrase:"
imageGen6_1 = "I am a professional artist seeking single-word responses, separated by commas, for an engaging image with the illusion of conversation. The subject should be a '1girl'. Please provide 35 descriptive words to create a conversational atmosphere. Example: '(1girl:1.1), Engaging, Conversation, Vodka, Borscht, Embroidery, Red Square, Folk Music, Onion Domes, Caviar, Matryoshka Dolls, Kremlin, Samovar, Cyrillic Alphabet, Traditions, Bolshoi Ballet, St. Basil's Cathedral, Blini, Russian Vodka Room, Zakuski, Balalaika, Pushkin, Soviet Union, Bear, Faberge Eggs, Siberia, St. Petersburg, Winter Palace, Taiga Forest, Tsar, Peterhof Palace, Russian Orthodox Church, Tchaikovsky, Rasputin, Hermitage Museum, Russian Federation.' The new sentence inspired by the following phrase:"
imageGen7 = "As a professional artist, seeking single-word responses, separated by commas, to conjure a vivid scene embodying the essence of dialogue. Choose between a '1girl' or '1boy' (at your discretion) as the focal point. Offer 35 evocative terms to craft an atmosphere of spirited exchange. Here an example how it should look like: '(1girl:1.1), Captivating, Banter, Espresso, Gelato, Frescoes, Piazza, Tarantella, Tuscan Hills, Truffles, Colosseum, Pasta, Gondola, Roman Forum, Heritage, La Scala Opera, Trevi Fountain, Cannoli, Aperitivo, Prosciutto, Vespa, Dante, Mediterranean, Wolf, Murano Glass, Amalfi Coast, Uffizi Gallery, Chianti Vineyards, Gladiator, Villa, Italian Renaissance, Michelangelo, Venetian Masks, Vatican City, Caravaggio, Sistine Chapel, Republic of Italy.' Envision a narrative influenced by this assemblage of words:"
imageGen8 = "As a professional artist, seeking single-word responses, separated by commas, to conjure a vivid scene embodying the essence of dialogue using GPT3. Choose between a '1girl' or '1boy' (at your discretion) as the focal point.  Here is an example of how it should look like: '(1girl:1.1), Captivating, Banter, Espresso, Gelato, Frescoes, Piazza, Tarantella, Tuscan Hills, Truffles, Colosseum, Pasta, Gondola, Roman Forum, Heritage, La Scala Opera, Trevi Fountain, Cannoli, Aperitivo, Prosciutto, Vespa, Dante, Mediterranean, Wolf, Murano Glass, Amalfi Coast, Uffizi Gallery, Chianti Vineyards, Gladiator, Villa, Italian Renaissance, Michelangelo, Venetian Masks, Vatican City, Caravaggio, Sistine Chapel, Republic of Italy' Create those words using this structure: 'Setting, time of day, season, weather, light, colors, textures, shapes, lines, perspective, foreground, middleground, background, scale, proportion, focal point, movement, space, contrast, repetition, unity, balance, atmosphere, flora, fauna, architecture, water features, sky, natural elements, human activity, transportation, cultural context, style, technique, artist's intention' Now offer 35 singleword, delimited by comma evocative terms to craft a similar atmosphere build on this german sentence (which first needs to be translated to english): "
imageGenForcedPreface = "((masterpiece,best quality)), solo, medium shot, looking at viewer, modern dresscode, pants, tshirt,  highly detailed, dramatic lighting, depth of field, (realistic:1.2), beautiful detailed face, detailed clothes, perspective, blonde hair, blue eyes, wallpaper, professional illustration,"
scenario ="converse with me. dont narrate. I will answer in the following texts. You are a girl named Emila. You start talking. Answer in a maximum of four sentences. The scenario is: "
scenarioGER ="Sprechen Sie mit mir als wäre ich ein 12 jähriger. Erzählen Sie nicht. Ich werde in den folgenden Texten antworten. Du bist ein Mädchen namens Emila. Sie beginnen zu sprechen. Antworten Sie in höchstens vier Sätzen. Das Szenario ist: "

def stableDifpayload(prompt):
    payload = {
                "enable_hr": True,
                "denoising_strength": 0.58, #use 0.52 if background elements are weird
                "firstphase_width": 768,
                "firstphase_height": 512,
                "hr_scale": 2,
                "hr_upscaler": "Latent (nearest-exact)",
                "hr_second_pass_steps": 20,
                "prompt": prompt,
                "seed": -1,
                "sampler_name": "DPM++ 2M Karras",
                "steps": 25,
                "cfg_scale": 7,
                "width": 768,
                "height": 512,
                "negative_prompt": "EasyNegative, badhandv4, nsfw, signature, patreon, extra fingers, fewer fingers",
                "eta": 31337,
            }
    return payload